@echo off
echo Starting StockBot...
echo Starting Backend...
start cmd /k ".venv\Scripts\uvicorn.exe main:app --reload"
echo Starting Frontend...
start cmd /k "cd frontend && npm run dev"
echo Done! App should be running at http://localhost:5173
